[package]
name = "axum-template"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
axum = { version = "0.7.7", features = ["macros"] }
tokio = { version = "1.41.0", features = ["full"] }
