[package]
name = "axum-template"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "app"
path = "src/bin/app.rs"

[workspace]
members = ["interfaces"]

[workspace.dependencies]
interfaces ={ path = "./interfaces" }
anyhow = "1.0.91"
axum = { version = "0.7.7", features = ["macros"] }
tokio = { version = "1.41.0", features = ["full"] }
serde = { version = "1.0.213", features = ["derive"]}

[dependencies]
interfaces.workspace = true
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
