[package]
name = "interfaces"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
serde.workspace = true
shaku_axum.workspace = true
usecases.workspace = true
utoipa.workspace = true
registry.workspace = true
